version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: oncodetect-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/heatmaps:/app/heatmaps
      - ./backend/oncodetect.db:/app/oncodetect.db
    environment:
      - DATABASE_URL=sqlite:///./oncodetect.db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: oncodetect-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped

networks:
  default:
    name: oncodetect-network
